version: '3'

services:

  redis:
    container_name: development-redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /opt/xcore/data/redis:/redis/data
    logging:
      driver: "json-file"
      options:
        max-size: "50MB"
        max-file: "1"

  postgresql:
    container_name: development-postgres
    image: postgres:9.4-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "development_database"
      POSTGRES_USER: "development_user"
      POSTGRES_PASSWORD: "development_password"
    volumes:
      - /opt/xcore/data/postgres:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:3.7.8-management
    container_name: development-rabbitmq
    hostname: "development"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "61613:61613"
    labels:
      NAME: "rabbitmq"
    volumes:
      - /opt/xcore/data/rabbitmq/lib:/var/lib/rabbitmq
      - /opt/xcore/data/rabbitmq/etc:/etc/rabbitmq
      - ./configs/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    entrypoint:
      bash -c "rabbitmq-plugins enable rabbitmq_stomp rabbitmq_management && rabbitmq-server"

  kurrento:
    image: kurento/kurento-media-server:latest
    container_name: development-kurrento
    ports:
      - "8888:8888"
    volumes:
      - /opt/xcore/files:/opt/xcore/files
