version: '3'

services:

  redis:
    container_name: development-redis
    image: redis:latest
    ports:
    - "6379:6379"
    expose:
    - 6379
    volumes:
    - ./storage/redis:/redis/data/
    logging:
      driver: "json-file"
      options:
        max-size: "50MB"
        max-file: "1"

  postgresql:
    container_name: development-postgres
    image: postgres:9.4-alpine
    restart: always
    expose:
    - 5432
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: "development_database"
      POSTGRES_USER: "development_user"
      POSTGRES_PASSWORD: "development_password"
    volumes:
    - ./storage/postgres:/var/lib/postgresql
