export enum EMetadataKeys {
  CONTROLLER_VALID = "CONTROLLER_VALID",
  CONTROLLER_MAPPING = "CONTROLLER_MAPPING",
  CONTROLLER_HANDLER_VALID = "CONTROLLER_HANDLER_VALID",
  CONTROLLER_HANDLER_MAPPING = "CONTROLLER_HANDLER_MAPPING",
  CONTROLLER_HANDLER_METHOD = "CONTROLLER_HANDLER_METHOD"
}

export enum ERequestMethod {
  GET = "GET",
  POST = "POST",
  DELETE = "DELETE"
}
